sudo: false
language: python

python:
  - 2.7
  - 3.6

env:
  - DJANGO_VERSION=18 DB=mysql
  - DJANGO_VERSION=19 DB=mysql
  - DJANGO_VERSION=110 DB=mysql
  - DJANGO_VERSION=111 DB=mysql
  - DJANGO_VERSION=18 DB=psql
  - DJANGO_VERSION=19 DB=psql
  - DJANGO_VERSION=110 DB=psql
  - DJANGO_VERSION=111 DB=psql
  - DJANGO_VERSION=18 DB=sqlite
  - DJANGO_VERSION=19 DB=sqlite
  - DJANGO_VERSION=110 DB=sqlite
  - DJANGO_VERSION=111 DB=sqlite
  - TOXENV=pre_commit

services:
  - mysql
  - postgresql

before_install:
  - if [[ -z $TOXENV ]]; then export TOXENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO_VERSION}-${DB}; fi
  - pip install codecov

install:
  - pip install tox

before_script:
  - mysql -e 'CREATE DATABASE regexfield;' -u root
  - psql -c 'CREATE DATABASE regexfield;' -U postgres

script:
  - tox

after_success:
  - if [[ -n $DJANGO_VERSION ]]; then codecov; fi;
